
#version of the docker compose syntax that we're going to using
version: '3.9'


#services is the main block inside docker compose file. Docker compose file typically consists of one or more services that needed for your application
services:

#name of the service 
  app:
   
  # We want to build the docker file inside our current directory. So the context that we're going to use for app service is the root directory that we are running the command from.

    build: 
      context: .

      #this line says if we're running using the docker compose, which we're only going to be using for development, build argument called dev and set it to true
      # args:
      #   - DEV=true


  #Port mappings. So this maps port 8000 on our local machine to port 8000 inside our docker container. This is how we can access the network when we want to connect to our server,

    ports:
      - "8000:8000"
  
  #Volumes are the ways of mapping directories from our systems into the docker container. So we are mapping the app directory that w created in the project to /app inside our container.
  # The reason we add this is because we want the updates that we make to our code in our local project to be reflected in the running container in real time. So we don't
  # want to have to rebuild the container everytime we change a line of code, we want to automatically sync the code in our project to the code running in the container.
    volumes:
      - ./app:/app
    
  #So this is the command that's used to run the services. We can override the command when we run Docker compose run. However, by default, if we don't specify a command, it's
  # going to use the command we define inside our docker compose file  
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
    # hostname of the database coz we're using docker compose, we can use the name of the service as the hostname so db is the name of the service that's going to be 
    # the hostname we connect to
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
# This tells the docker compose that the app service depends on db service. So it will try and wait for the DB service to start before it starts the app services and if
# the db service fails then it will automatically assume that app is going to fail and it shuts down the app service
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data

    # It sets 3 environment variables. POSTGRES_DB is to set the initial database configuration for our new DB service. So when our db first starts, it's going to create a 
    # database and a named inside db called devdb and then it's going to create a user and set the password. This is just the details for our local development server. 
    # This is not what we're going to be using if we were deploy this to an actual server that's running coz if that's the case, then you shouldn't be hard coding real credentials 
    # inside your source code.
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  # name of our volume. It is just going to store it in the default location on the file system that it does for the name volumes
  dev-db-data:

    
#Now we need to add similar environment variables to our app service and this is going to tell our app how to connect to the database and we're going to be configuring Django
# a bit later to pulling these values and use them for the databse connection
