# This --- signifies it is yml file
---
name: Checks

# This is the trigger. So we're saying we want this particular GitHub actions to run on push, which means any push of changes to our project. So any time we do git command and then push it up
# Github, it's going to run the jobs that we specify inside the checks.yml file
on: [push] 

jobs: 
# It defines new job called test-lint and this is actually id of the job and you want to use id like this because it might need to be referenced somewhere else inside github actions. You
# might want to ensure the order of the jobs runs in a certain way. You might want to wait on certain jobs to complete before other job continue.
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    # steps are the different things that run for the job
    steps: 
    # name is the name of this step
    
      - name: Login to Docker Hub

      # uses allows you to use another pre-made action that's provided in the 
    # Github actions repository. An action is basically just a Docker container 
    # and a Docker configuration that's set up to perform a certain task. And this
    # particular action is docker/login-action@v1 and this action is used to login
    # into a docker
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          Password: ${{secrets.DOCKERHUB_TOKEN}}
    #  Checkout one does is an action that's provided by a GitHub automatically or provided by 
    #  premade for free. The reason we need to do this is because by default the code is not checked
    # out inside the job that we,re running.The reason for this is because sometimes you 
    # may not need to  check out the code, so there might be certain jobs that you want to perform 
    # that don't require the code in order to perform these jobs.However in our case 
    # we need to access the code because we need to run test and linting on the code.
    # So we need to use this check out step here to make sure the code is available
    # for us to run the text
      - name: Checkout
      # It is going to be performed if the Docker log in step completed successfully.And basically it checks our code out inside our GitHub actions jobs
        uses: actions/checkout@v2


      - name: Test

      # So this is the command that runs the unit tests on our project
        run: docker-compose run --rm app sh -c "python manage.py test"


      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"



